import blockContent from './blockContent'
import blogCategory from './blogCategory'
import post from './post'
import serviceContent from './serviceContent'
import faqContent from './faqContent'
import mbaCourses from './mbaCourses'
import accordionBlock from './accordionBlock'
import { table } from 'console'
import customTable from './customTable'
export const schemaTypes = [post, blockContent, serviceContent,blogCategory,customTable,faqContent,mbaCourses,accordionBlock]
